export { default as api } from "./__config";
export { apoderadosApi } from "./apoderados";
export { asignaturasApi } from "./asignaturas";
export { authApi } from "./auth";
export { catalogosApi } from "./catalogos";
export { cursosApi } from "./cursos";
export { dashboardApi } from "./dashboard";
export { estudiantesApi } from "./estudiantes";
export { matriculasApi } from "./matriculas";
export { periodosApi } from "./periodos";
export { profesoresApi } from "./profesores";
export { usuariosApi } from "./usuarios";
